WIP: Create gh CI action
tandemdrive/ocpi-tariffs pull request #4
Opened 2023-03-28 10:56 UTC by remkop22

2023-03-28 12:50 UTC, bheylin reviewed
I would look at another workflow for inspiration:

https://github.com/dtolnay/anyhow/blob/master/.github/workflows/ci.yml

2023-03-28 14:58 UTC, bheylin commented on .github/workflows/rust.yml
Nice! That's clearer to read :wink:

2023-03-29 08:49 UTC, bheylin requested changes

2023-03-29 09:17 UTC, remkop22 commented on .github/workflows/rust.yml
> +    - run: cargo build --verbose
According to cargo docs target selection if no package is passed, is based on the current directory, and for virtual workspaces, this includes all members

2023-03-29 09:17 UTC, remkop22 commented on .github/workflows/rust.yml
> +    - run: cargo build --verbose
Hmm, but maybe it's nice to be explicit anyway... I'll change it

2023-03-29 11:13 UTC, bheylin approved these changes

2023-03-29 11:40 UTC, merged